In [1]:
import mysql.connector
import pandas as pd 
import json
import numpy as np
import MySQLdb
import MySQLdb.cursors

In [2]:
db_thread = MySQLdb.connect("127.0.0.1", "root", "andhika", "usek_monev", cursorclass=MySQLdb.cursors.DictCursor)
cur_thread = db_thread.cursor()
print(cur_thread)

<MySQLdb.cursors.DictCursor object at 0x7fa89f18f7c0>

In [7]:
def get_paket():
    sql = "SELECT * FROM paket where nilai_rata_rata is null"
    cur_thread.execute(sql)
    paket = cur_thread.fetchall()
    return paket

In [8]:
def get_ujian_siswa(paket_id):
    sql = "select * from ujian_siswa where paket_id='%s' and status > 1" % (paket_id)
    ujian_siswa = pd.read_sql(sql, con=db_thread)
    ujian_siswa = ujian_siswa.set_index('id') 
    return ujian_siswa

In [9]:
def update_nilai_rata2_paket(paket):
    try:
        sql = "update paket set nilai_rata_rata=%.4f where id='%s'" % (paket['nilai_rata_rata'], paket['id'])
        cur_thread.execute(sql)
        db_thread.commit()
    except:
        print(paket['nilai_rata_rata'], paket['nama'])

In [10]:
def get_nilai_rata2(hasil_sum):
    jumlah_soal = hasil_sum[4] + hasil_sum[5] + hasil_sum[6] -  (ujian_siswas['jawaban_siswa'].count()*5)
    nilai_rata2 = hasil_sum[4] / (jumlah_soal)
    return nilai_rata2

In [ ]:
pakets = get_paket()
for paket in pakets:
    print(paket['nama'])
    ujian_siswas = get_ujian_siswa(paket['id'])
    paket['nilai_rata_rata'] = get_nilai_rata2(ujian_siswas.sum())
    update_nilai_rata2_paket(paket)
db_thread.commit()

KTSP_Bahasa_Indonesia_Bahasa_3
nan KTSP_Bahasa_Indonesia_Bahasa_3
KTSP_Bahasa_Indonesia_Bahasa_4
nan KTSP_Bahasa_Indonesia_Bahasa_4
KTSP_Bahasa_Indonesia_Bahasa_5

<ipython-input-10-1784f63f23cb>:3: RuntimeWarning: invalid value encountered in double_scalars
  nilai_rata2 = hasil_sum[4] / (jumlah_soal)

nan KTSP_Bahasa_Indonesia_Bahasa_5
KTSP_Sastra_Indonesia_5
nan KTSP_Sastra_Indonesia_5
KTSP_Sastra_Indonesia_4
nan KTSP_Sastra_Indonesia_4
KTSP_Matematika_IPA_5
nan KTSP_Matematika_IPA_5
KTSP_Matematika_IPS_1
nan KTSP_Matematika_IPS_1
KTSP_Matematika_IPS_2
nan KTSP_Matematika_IPS_2
KTSP_Matematika_IPS_3
nan KTSP_Matematika_IPS_3
KTSP_Matematika_IPS_4
nan KTSP_Matematika_IPS_4
KTSP_Matematika_IPS_5
nan KTSP_Matematika_IPS_5
KTSP_Bahasa_Inggris_3
nan KTSP_Bahasa_Inggris_3
KTSP_Bahasa_Inggris_4
nan KTSP_Bahasa_Inggris_4
KTSP_Bahasa_Inggris_5
nan KTSP_Bahasa_Inggris_5
KTSP_Seni_Rupa_5
nan KTSP_Seni_Rupa_5
KTSP_Seni_Musik_5
nan KTSP_Seni_Musik_5
KTSP_Seni_Tari_5
nan KTSP_Seni_Tari_5
KTSP_Seni_Teater_5
nan KTSP_Seni_Teater_5
KTSP_Pendidikan_Jasmani,_olahraga,_dan_Kesehatan_5
nan KTSP_Pendidikan_Jasmani,_olahraga,_dan_Kesehatan_5
KTSP_Teknologi_Informasi_dan_Komunikasi_5
nan KTSP_Teknologi_Informasi_dan_Komunikasi_5
KTSP_Bahasa_Jerman_3
nan KTSP_Bahasa_Jerman_3
KTSP_Bahasa_Jerman_4
nan KTSP_Bahasa_Jerman_4
KTSP_Bahasa_Jerman_5
nan KTSP_Bahasa_Jerman_5
KTSP_Bahasa_Jepang_5
nan KTSP_Bahasa_Jepang_5
KTSP_Bahasa_Arab_3
nan KTSP_Bahasa_Arab_3
KTSP_Bahasa_Arab_4
nan KTSP_Bahasa_Arab_4
KTSP_Bahasa_Arab_5
nan KTSP_Bahasa_Arab_5
KTSP_Bahasa_Mandarin_1
nan KTSP_Bahasa_Mandarin_1
KTSP_Bahasa_Mandarin_2
nan KTSP_Bahasa_Mandarin_2
KTSP_Bahasa_Mandarin_5
nan KTSP_Bahasa_Mandarin_5
KTSP_Bahasa_Jawa_5
nan KTSP_Bahasa_Jawa_5
KTSP_Bahasa_Madura_2
nan KTSP_Bahasa_Madura_2
KTSP_Bahasa_Madura_3
nan KTSP_Bahasa_Madura_3
KTSP_Bahasa_Madura_4
nan KTSP_Bahasa_Madura_4
KTSP_Bahasa_Madura_5
nan KTSP_Bahasa_Madura_5
KTSP_Biologi_5
nan KTSP_Biologi_5
KTSP_Fisika_5
nan KTSP_Fisika_5
KTSP_Kimia_2
nan KTSP_Kimia_2
KTSP_Kimia_4
nan KTSP_Kimia_4
KTSP_Kimia_5
nan KTSP_Kimia_5
KTSP_Geografi_5
nan KTSP_Geografi_5
KTSP_Ekonomi_5
nan KTSP_Ekonomi_5
KTSP_Sosiologi_5
nan KTSP_Sosiologi_5
KTSP_Antropologi_3
nan KTSP_Antropologi_3
KTSP_Antropologi_4
nan KTSP_Antropologi_4
KTSP_Antropologi_5
nan KTSP_Antropologi_5
KTSP_Matematika_BAHASA_3
nan KTSP_Matematika_BAHASA_3
KTSP_Matematika_BAHASA_4
nan KTSP_Matematika_BAHASA_4
KTSP_Matematika_BAHASA_5
nan KTSP_Matematika_BAHASA_5
KTSP_Pendidikan_Agama_Islam_dan_Budi_Pekerti_2
nan KTSP_Pendidikan_Agama_Islam_dan_Budi_Pekerti_2
KTSP_Pendidikan_Agama_Hindu_dan_Budi_Pekerti_2
nan KTSP_Pendidikan_Agama_Hindu_dan_Budi_Pekerti_2
KTSP_Pendidikan_Agama_Hindu_dan_Budi_Pekerti_3
nan KTSP_Pendidikan_Agama_Hindu_dan_Budi_Pekerti_3
K13_Bahasa_dan_Sastra_Indonesia_3
nan K13_Bahasa_dan_Sastra_Indonesia_3
K13_Bahasa_dan_Sastra_Indonesia_5
nan K13_Bahasa_dan_Sastra_Indonesia_5
K13_Matematika_Umum_5
nan K13_Matematika_Umum_5
K13_Matematika_Peminatan_MIPA_5
nan K13_Matematika_Peminatan_MIPA_5
K13_Bahasa_Inggris_5
nan K13_Bahasa_Inggris_5
K13_Bahasa_dan_Sastra_Inggris_(Peminatan)_1
nan K13_Bahasa_dan_Sastra_Inggris_(Peminatan)_1
K13_Bahasa_dan_Sastra_Inggris_(Peminatan)_5
nan K13_Bahasa_dan_Sastra_Inggris_(Peminatan)_5
K13_Sejarah_Peminatan_IPS_5
nan K13_Sejarah_Peminatan_IPS_5
K13_Seni_Rupa_5
nan K13_Seni_Rupa_5
K13_Seni_Musik_5
nan K13_Seni_Musik_5
K13_Seni_Tari_5
nan K13_Seni_Tari_5
K13_Seni_Teater_5
nan K13_Seni_Teater_5
K13_Pendidikan_Jasmani,_olahraga,_dan_Kesehatan_5
nan K13_Pendidikan_Jasmani,_olahraga,_dan_Kesehatan_5
K13_Kerajinan_2
K13_Kerajinan_3
K13_Kerajinan_4
K13_Kerajinan_5
nan K13_Kerajinan_5
K13_Rekayasa_1
K13_Rekayasa_2
K13_Rekayasa_3
K13_Rekayasa_4
K13_Rekayasa_5
nan K13_Rekayasa_5
K13_Budidaya_1
K13_Budidaya_2
K13_Budidaya_3
K13_Budidaya_4
K13_Budidaya_5
nan K13_Budidaya_5
K13_Pengolahan_1
K13_Pengolahan_2
K13_Pengolahan_3
K13_Pengolahan_4
K13_Pengolahan_5
nan K13_Pengolahan_5
K13_Bahasa_dan_Sastra_Jerman_1
K13_Bahasa_dan_Sastra_Jerman_2
K13_Bahasa_dan_Sastra_Jerman_3
K13_Bahasa_dan_Sastra_Jerman_4
K13_Bahasa_dan_Sastra_Jerman_5
nan K13_Bahasa_dan_Sastra_Jerman_5
K13_Bahasa_dan_Sastra_Jepang_1
K13_Bahasa_dan_Sastra_Jepang_2
K13_Bahasa_dan_Sastra_Jepang_3
K13_Bahasa_dan_Sastra_Jepang_4
K13_Bahasa_dan_Sastra_Jepang_5
nan K13_Bahasa_dan_Sastra_Jepang_5
K13_Bahasa_dan_Sastra_Perancis_1
nan K13_Bahasa_dan_Sastra_Perancis_1
K13_Bahasa_dan_Sastra_Perancis_2
K13_Bahasa_dan_Sastra_Perancis_4
K13_Bahasa_dan_Sastra_Perancis_3
nan K13_Bahasa_dan_Sastra_Perancis_3
K13_Bahasa_dan_Sastra_Perancis_5
nan K13_Bahasa_dan_Sastra_Perancis_5
K13_Bahasa_dan_Sastra_Arab_1
K13_Bahasa_dan_Sastra_Arab_2
K13_Bahasa_dan_Sastra_Arab_3
K13_Bahasa_dan_Sastra_Arab_4
K13_Bahasa_dan_Sastra_Arab_5
nan K13_Bahasa_dan_Sastra_Arab_5
K13_Bahasa_dan_Sastra_Mandarin_1
K13_Bahasa_dan_Sastra_Mandarin_2
K13_Bahasa_dan_Sastra_Mandarin_3
K13_Bahasa_dan_Sastra_Mandarin_4
K13_Bahasa_dan_Sastra_Mandarin_5
nan K13_Bahasa_dan_Sastra_Mandarin_5
K13_Bahasa_dan_Sastra_Korea_1
K13_Bahasa_dan_Sastra_Korea_2
K13_Bahasa_Jawa_1
K13_Bahasa_Jawa_2
K13_Bahasa_Jawa_3
K13_Bahasa_Jawa_4
K13_Bahasa_Jawa_5
nan K13_Bahasa_Jawa_5
K13_Bahasa_Madura_1
K13_Bahasa_Madura_2
nan K13_Bahasa_Madura_2
K13_Bahasa_Madura_3
nan K13_Bahasa_Madura_3
K13_Bahasa_Madura_4
nan K13_Bahasa_Madura_4
K13_Bahasa_Madura_5
nan K13_Bahasa_Madura_5
K13_Biologi_1
K13_Biologi_2
K13_Biologi_3
K13_Biologi_4
K13_Biologi_5
nan K13_Biologi_5
K13_Fisika_1
K13_Fisika_2
K13_Fisika_3
K13_Fisika_4
K13_Fisika_5
nan K13_Fisika_5
K13_Kimia_1
K13_Kimia_2
K13_Kimia_3
K13_Kimia_4
K13_Kimia_5
nan K13_Kimia_5
K13_Geografi_1
K13_Geografi_3
K13_Geografi_4
K13_Geografi_5
nan K13_Geografi_5
K13_Geografi_2
K13_Ekonomi_1
K13_Ekonomi_2
K13_Ekonomi_3
K13_Ekonomi_4
K13_Ekonomi_5
nan K13_Ekonomi_5
K13_Sosiologi_1
K13_Sosiologi_2